//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accunting.DataLayer.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accunting
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int TypeId { get; set; }
        public int Amount { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual AccuntingType AccuntingType { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
