USE [master]
GO

/****** Object:  Database [Accunting_db]    Script Date: 2/1/2021 5:38:15 AM ******/
CREATE DATABASE [Accunting_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Accunting_db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Accunting_db.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Accunting_db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Accunting_db_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Accunting_db] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Accunting_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Accunting_db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Accunting_db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Accunting_db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Accunting_db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Accunting_db] SET ARITHABORT OFF 
GO

ALTER DATABASE [Accunting_db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Accunting_db] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Accunting_db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Accunting_db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Accunting_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Accunting_db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Accunting_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Accunting_db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Accunting_db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Accunting_db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Accunting_db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Accunting_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Accunting_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Accunting_db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Accunting_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Accunting_db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Accunting_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Accunting_db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Accunting_db] SET RECOVERY FULL 
GO

ALTER DATABASE [Accunting_db] SET  MULTI_USER 
GO

ALTER DATABASE [Accunting_db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Accunting_db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Accunting_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Accunting_db] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Accunting_db] SET  READ_WRITE 
GO

